version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        container_name: 'app'
        restart: always
        env_file:
            - .env
        ports:
            - '3000:${APP_PORT}'
        networks:
            - localnet
    cronjob:
        container_name: cronjob
        build:
            context: .
            dockerfile: Dockerfile.cronjobs
        restart: always
        networks:
            - localnet

networks:
    localnet:
