FROM node:18.14.0-alpine3.17
RUN apk update
RUN apk add python3
RUN apk add --no-cache --upgrade grep
WORKDIR /app
COPY package*.json .
RUN npm install -g node-pre-gyp
RUN npm install
COPY . .
RUN npm run build
RUN chmod go+rwx /app/cronjobs.sh
RUN /app/cronjobs.sh
CMD ["crond", "-f", "-l", "2"]